/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArticleInput {
  'coverImageUrl' : string,
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'excerpt' : string,
  'category' : Category,
}
export interface ArticleView {
  'id' : bigint,
  'coverImageUrl' : string,
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'publishedAt' : Time,
  'bookmarks' : Array<Principal>,
  'author' : Principal,
  'likes' : Array<Principal>,
  'excerpt' : string,
  'category' : Category,
}
export type Category = { 'finance' : null } |
  { 'economicHistory' : null } |
  { 'stock' : null } |
  { 'crypto' : null } |
  { 'property' : null };
export interface Comment {
  'id' : bigint,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'articleId' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'writer' : null } |
  { 'reader' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createArticle' : ActorMethod<[ArticleInput], bigint>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'getAllArticles' : ActorMethod<[], Array<ArticleView>>,
  'getArticle' : ActorMethod<[bigint], ArticleView>,
  'getArticlesFromAuthor' : ActorMethod<[Principal], Array<ArticleView>>,
  'getArticlesFromCategory' : ActorMethod<[Category], Array<ArticleView>>,
  'getBookmarkedArticles' : ActorMethod<[Principal], Array<ArticleView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getComment' : ActorMethod<[bigint], Comment>,
  'getCommentsForArticle' : ActorMethod<[bigint], Array<Comment>>,
  'getLikeCount' : ActorMethod<[bigint], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserBookmarkedArticle' : ActorMethod<[bigint, Principal], boolean>,
  'hasUserLikedArticle' : ActorMethod<[bigint, Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postComment' : ActorMethod<[bigint, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchArticles' : ActorMethod<[string], Array<ArticleView>>,
  'toggleBookmarkArticle' : ActorMethod<[bigint], boolean>,
  'toggleLikeArticle' : ActorMethod<[bigint], boolean>,
  'updateArticle' : ActorMethod<[bigint, ArticleInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];