/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'finance' : IDL.Null,
  'economicHistory' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
  'property' : IDL.Null,
});
export const ArticleInput = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : Category,
});
export const Time = IDL.Int;
export const ArticleView = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Time,
  'bookmarks' : IDL.Vec(IDL.Principal),
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'excerpt' : IDL.Text,
  'category' : Category,
});
export const UserRole = IDL.Variant({
  'writer' : IDL.Null,
  'reader' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'articleId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createArticle' : IDL.Func([ArticleInput], [IDL.Nat], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(ArticleView)], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [ArticleView], ['query']),
  'getArticlesFromAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ArticleView)],
      ['query'],
    ),
  'getArticlesFromCategory' : IDL.Func(
      [Category],
      [IDL.Vec(ArticleView)],
      ['query'],
    ),
  'getBookmarkedArticles' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ArticleView)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getComment' : IDL.Func([IDL.Nat], [Comment], ['query']),
  'getCommentsForArticle' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserBookmarkedArticle' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'hasUserLikedArticle' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(ArticleView)], ['query']),
  'toggleBookmarkArticle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleLikeArticle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateArticle' : IDL.Func([IDL.Nat, ArticleInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'finance' : IDL.Null,
    'economicHistory' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
    'property' : IDL.Null,
  });
  const ArticleInput = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : Category,
  });
  const Time = IDL.Int;
  const ArticleView = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Time,
    'bookmarks' : IDL.Vec(IDL.Principal),
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'excerpt' : IDL.Text,
    'category' : Category,
  });
  const UserRole = IDL.Variant({ 'writer' : IDL.Null, 'reader' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'articleId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createArticle' : IDL.Func([ArticleInput], [IDL.Nat], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(ArticleView)], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [ArticleView], ['query']),
    'getArticlesFromAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ArticleView)],
        ['query'],
      ),
    'getArticlesFromCategory' : IDL.Func(
        [Category],
        [IDL.Vec(ArticleView)],
        ['query'],
      ),
    'getBookmarkedArticles' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ArticleView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getComment' : IDL.Func([IDL.Nat], [Comment], ['query']),
    'getCommentsForArticle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserBookmarkedArticle' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'hasUserLikedArticle' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(ArticleView)], ['query']),
    'toggleBookmarkArticle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleLikeArticle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateArticle' : IDL.Func([IDL.Nat, ArticleInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };